version: '2'
services: 
    postgres:
        build:
            context: ./postgres
        ports:
            - "5432:5432"
        volumes: 
            - ../sqldata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=gina
            - POSTGRES_PASSWORD=examplepasswd
            - POSTGRES_DB=maindb
        
    jupyter:
        build:
            context: ./jupyter
        ports:
            - "8888:8888"
            - "5656:5656"
        user: root
        environment:
            - NB_UID=1000
            - NB_GID=1000
        volumes: 
            - ../notebooks:/home/jovyan/work 
        depends_on: 
            - postgres
        links: 
            - "postgres:postgresdb"


        
